import { pokemonTypes } from './pokemon-types';
export const allPokemon = [
  {
    name: 'Bulbasaur',
    levelRate: [1, 15],
    pokedexId: 1,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Ivysaur',
    levelRate: [15, 35],
    pokedexId: 2,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Venusaur',
    levelRate: [35, 100],
    pokedexId: 3,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Charmander',
    levelRate: [1, 15],
    pokedexId: 4,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Charmeleon',
    levelRate: [15, 35],
    pokedexId: 5,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Charizard',
    levelRate: [35, 100],
    pokedexId: 6,
    elements: [pokemonTypes.FIRE, pokemonTypes.FLYING],
  },
  {
    name: 'Squirtle',
    levelRate: [1, 15],
    pokedexId: 7,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Wartortle',
    levelRate: [15, 35],
    pokedexId: 8,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Blastoise',
    levelRate: [35, 100],
    pokedexId: 9,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Caterpie',
    levelRate: [1, 15],
    pokedexId: 10,
    elements: [pokemonTypes.BUG],
  },
  {
    name: 'Metapod',
    levelRate: [15, 35],
    pokedexId: 11,
    elements: [pokemonTypes.BUG],
  },
  {
    name: 'Butterfree',
    levelRate: [35, 100],
    pokedexId: 12,
    elements: [pokemonTypes.BUG, pokemonTypes.FLYING],
  },
  {
    name: 'Weedle',
    levelRate: [1, 15],
    pokedexId: 13,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Kakuna',
    levelRate: [15, 35],
    pokedexId: 14,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Beedrill',
    levelRate: [35, 100],
    pokedexId: 15,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Pidgey',
    levelRate: [1, 15],
    pokedexId: 16,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Pidgeotto',
    levelRate: [15, 35],
    pokedexId: 17,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Pidgeot',
    levelRate: [35, 100],
    pokedexId: 18,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Rattata',
    levelRate: [1, 15],
    pokedexId: 19,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Raticate',
    levelRate: [16, 100],
    pokedexId: 20,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Spearow',
    levelRate: [1, 15],
    pokedexId: 21,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Fearow',
    levelRate: [16, 100],
    pokedexId: 22,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Ekans',
    levelRate: [1, 15],
    pokedexId: 23,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Arbok',
    levelRate: [16, 100],
    pokedexId: 24,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Pikachu',
    levelRate: [1, 15],
    pokedexId: 25,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Raichu',
    levelRate: [16, 100],
    pokedexId: 26,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Sandshrew',
    levelRate: [1, 15],
    pokedexId: 27,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Sandslash',
    levelRate: [16, 100],
    pokedexId: 28,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Nidoran♀',
    levelRate: [1, 15],
    pokedexId: 29,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Nidorina',
    levelRate: [15, 35],
    pokedexId: 30,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Nidoqueen',
    levelRate: [35, 100],
    pokedexId: 31,
    elements: [pokemonTypes.POISON, pokemonTypes.GROUND],
  },
  {
    name: 'Nidoran♂',
    levelRate: [1, 15],
    pokedexId: 32,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Nidorino',
    levelRate: [15, 35],
    pokedexId: 33,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Nidoking',
    levelRate: [35, 100],
    pokedexId: 34,
    elements: [pokemonTypes.POISON, pokemonTypes.GROUND],
  },
  {
    name: 'Clefairy',
    levelRate: [1, 15],
    pokedexId: 35,
    elements: [pokemonTypes.FAIRY],
  },
  {
    name: 'Clefable',
    levelRate: [15, 100],
    pokedexId: 36,
    elements: [pokemonTypes.FAIRY],
  },
  {
    name: 'Vulpix',
    levelRate: [1, 15],
    pokedexId: 37,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Ninetales',
    levelRate: [16, 100],
    pokedexId: 38,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Jigglypuff',
    levelRate: [1, 15],
    pokedexId: 39,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FAIRY],
  },
  {
    name: 'Wigglytuff',
    levelRate: [16, 100],
    pokedexId: 40,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FAIRY],
  },
  {
    name: 'Zubat',
    levelRate: [1, 15],
    pokedexId: 41,
    elements: [pokemonTypes.POISON, pokemonTypes.FLYING],
  },
  {
    name: 'Golbat',
    levelRate: [16, 100],
    pokedexId: 42,
    elements: [pokemonTypes.POISON, pokemonTypes.FLYING],
  },
  {
    name: 'Oddish',
    levelRate: [1, 15],
    pokedexId: 43,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Gloom',
    levelRate: [15, 35],
    pokedexId: 44,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Vileplume',
    levelRate: [36, 100],
    pokedexId: 45,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Paras',
    levelRate: [1, 15],
    pokedexId: 46,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Parasect',
    levelRate: [16, 100],
    pokedexId: 47,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Venonat',
    levelRate: [1, 15],
    pokedexId: 48,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Venomoth',
    levelRate: [16, 100],
    pokedexId: 49,
    elements: [pokemonTypes.BUG, pokemonTypes.POISON],
  },
  {
    name: 'Diglett',
    levelRate: [1, 15],
    pokedexId: 50,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Dugtrio',
    levelRate: [16, 100],
    pokedexId: 51,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Meowth',
    levelRate: [1, 15],
    pokedexId: 52,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Persian',
    levelRate: [16, 100],
    pokedexId: 53,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Psyduck',
    levelRate: [1, 15],
    pokedexId: 54,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Golduck',
    levelRate: [16, 100],
    pokedexId: 55,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Mankey',
    levelRate: [1, 15],
    pokedexId: 56,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Primeape',
    levelRate: [16, 100],
    pokedexId: 57,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Growlithe',
    levelRate: [1, 15],
    pokedexId: 58,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Arcanine',
    levelRate: [16, 100],
    pokedexId: 59,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Poliwag',
    levelRate: [1, 15],
    pokedexId: 60,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Poliwhirl',
    levelRate: [15, 35],
    pokedexId: 61,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Poliwrath',
    levelRate: [36, 100],
    pokedexId: 62,
    elements: [pokemonTypes.WATER, pokemonTypes.FIGHTING],
  },
  {
    name: 'Abra',
    levelRate: [1, 15],
    pokedexId: 63,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Kadabra',
    levelRate: [15, 35],
    pokedexId: 64,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Alakazam',
    levelRate: [36, 100],
    pokedexId: 65,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Machop',
    levelRate: [1, 15],
    pokedexId: 66,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Machoke',
    levelRate: [15, 35],
    pokedexId: 67,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Machamp',
    levelRate: [36, 100],
    pokedexId: 68,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Bellsprout',
    levelRate: [1, 15],
    pokedexId: 69,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Weepinbell',
    levelRate: [15, 35],
    pokedexId: 70,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Victreebel',
    levelRate: [36, 100],
    pokedexId: 71,
    elements: [pokemonTypes.GRASS, pokemonTypes.POISON],
  },
  {
    name: 'Tentacool',
    levelRate: [1, 15],
    pokedexId: 72,
    elements: [pokemonTypes.WATER, pokemonTypes.POISON],
  },
  {
    name: 'Tentacruel',
    levelRate: [16, 100],
    pokedexId: 73,
    elements: [pokemonTypes.WATER, pokemonTypes.POISON],
  },
  {
    name: 'Geodude',
    levelRate: [1, 15],
    pokedexId: 74,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Graveler',
    levelRate: [15, 35],
    pokedexId: 75,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Golem',
    levelRate: [36, 100],
    pokedexId: 76,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Ponyta',
    levelRate: [1, 15],
    pokedexId: 77,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Rapidash',
    levelRate: [16, 100],
    pokedexId: 78,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Slowpoke',
    levelRate: [1, 15],
    pokedexId: 79,
    elements: [pokemonTypes.WATER, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Slowbro',
    levelRate: [16, 100],
    pokedexId: 80,
    elements: [pokemonTypes.WATER, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Magnemite',
    levelRate: [1, 15],
    pokedexId: 81,
    elements: [pokemonTypes.ELECTRIC, pokemonTypes.STEEL],
  },
  {
    name: 'Magneton',
    levelRate: [16, 100],
    pokedexId: 82,
    elements: [pokemonTypes.ELECTRIC, pokemonTypes.STEEL],
  },
  {
    name: "Farfetch'd",
    levelRate: [0, 66],
    pokedexId: 83,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Doduo',
    levelRate: [1, 15],
    pokedexId: 84,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Dodrio',
    levelRate: [16, 100],
    pokedexId: 85,
    elements: [pokemonTypes.NORMAL, pokemonTypes.FLYING],
  },
  {
    name: 'Seel',
    levelRate: [1, 15],
    pokedexId: 86,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Dewgong',
    levelRate: [16, 100],
    pokedexId: 87,
    elements: [pokemonTypes.WATER, pokemonTypes.ICE],
  },
  {
    name: 'Grimer',
    levelRate: [1, 15],
    pokedexId: 88,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Muk',
    levelRate: [16, 100],
    pokedexId: 89,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Shellder',
    levelRate: [1, 15],
    pokedexId: 90,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Cloyster',
    levelRate: [16, 100],
    pokedexId: 91,
    elements: [pokemonTypes.WATER, pokemonTypes.ICE],
  },
  {
    name: 'Gastly',
    levelRate: [1, 15],
    pokedexId: 92,
    elements: [pokemonTypes.GHOST, pokemonTypes.POISON],
  },
  {
    name: 'Haunter',
    levelRate: [15, 35],
    pokedexId: 93,
    elements: [pokemonTypes.GHOST, pokemonTypes.POISON],
  },
  {
    name: 'Gengar',
    levelRate: [36, 100],
    pokedexId: 94,
    elements: [pokemonTypes.GHOST, pokemonTypes.POISON],
  },
  {
    name: 'Onix',
    levelRate: [18, 66],
    pokedexId: 95,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Drowzee',
    levelRate: [1, 15],
    pokedexId: 96,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Hypno',
    levelRate: [16, 100],
    pokedexId: 97,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Krabby',
    levelRate: [1, 15],
    pokedexId: 98,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Kingler',
    levelRate: [16, 100],
    pokedexId: 99,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Voltorb',
    levelRate: [1, 15],
    pokedexId: 100,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Electrode',
    levelRate: [16, 100],
    pokedexId: 101,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Exeggcute',
    levelRate: [1, 15],
    pokedexId: 102,
    elements: [pokemonTypes.GRASS, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Exeggutor',
    levelRate: [16, 100],
    pokedexId: 103,
    elements: [pokemonTypes.GRASS, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Cubone',
    levelRate: [1, 15],
    pokedexId: 104,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Marowak',
    levelRate: [16, 100],
    pokedexId: 105,
    elements: [pokemonTypes.GROUND],
  },
  {
    name: 'Hitmonlee',
    levelRate: [5, 66],
    pokedexId: 106,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Hitmonchan',
    levelRate: [5, 66],
    pokedexId: 107,
    elements: [pokemonTypes.FIGHTING],
  },
  {
    name: 'Lickitung',
    levelRate: [5, 66],
    pokedexId: 108,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Koffing',
    levelRate: [1, 15],
    pokedexId: 109,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Weezing',
    levelRate: [16, 100],
    pokedexId: 110,
    elements: [pokemonTypes.POISON],
  },
  {
    name: 'Rhyhorn',
    levelRate: [1, 15],
    pokedexId: 111,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Rhydon',
    levelRate: [16, 100],
    pokedexId: 112,
    elements: [pokemonTypes.ROCK, pokemonTypes.GROUND],
  },
  {
    name: 'Chansey',
    levelRate: [5, 66],
    pokedexId: 113,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Tangela',
    levelRate: [5, 66],
    pokedexId: 114,
    elements: [pokemonTypes.GRASS],
  },
  {
    name: 'Kangaskhan',
    levelRate: [5, 66],
    pokedexId: 115,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Horsea',
    levelRate: [1, 15],
    pokedexId: 116,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Seadra',
    levelRate: [16, 100],
    pokedexId: 117,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Goldeen',
    levelRate: [1, 15],
    pokedexId: 118,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Seaking',
    levelRate: [16, 100],
    pokedexId: 119,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Staryu',
    levelRate: [1, 15],
    pokedexId: 120,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Starmie',
    levelRate: [16, 100],
    pokedexId: 121,
    elements: [pokemonTypes.WATER, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Mr. Mime',
    levelRate: [5, 66],
    pokedexId: 122,
    elements: [pokemonTypes.PSYCHIC, pokemonTypes.FAIRY],
  },
  {
    name: 'Scyther',
    levelRate: [5, 66],
    pokedexId: 123,
    elements: [pokemonTypes.BUG, pokemonTypes.FLYING],
  },
  {
    name: 'Jynx',
    levelRate: [5, 66],
    pokedexId: 124,
    elements: [pokemonTypes.ICE, pokemonTypes.PSYCHIC],
  },
  {
    name: 'Electabuzz',
    levelRate: [5, 66],
    pokedexId: 125,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Magmar',
    levelRate: [5, 66],
    pokedexId: 126,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Pinsir',
    levelRate: [5, 66],
    pokedexId: 127,
    elements: [pokemonTypes.BUG],
  },
  {
    name: 'Tauros',
    levelRate: [5, 66],
    pokedexId: 128,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Magikarp',
    levelRate: [1, 5],
    pokedexId: 129,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Gyarados',
    levelRate: [32, 100],
    pokedexId: 130,
    elements: [pokemonTypes.WATER, pokemonTypes.FLYING],
  },
  {
    name: 'Lapras',
    levelRate: [32, 66],
    pokedexId: 131,
    elements: [pokemonTypes.WATER, pokemonTypes.ICE],
  },
  {
    name: 'Ditto',
    levelRate: [1, 100],
    pokedexId: 132,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Eevee',
    levelRate: [5, 12],
    pokedexId: 133,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Vaporeon',
    levelRate: [16, 100],
    pokedexId: 134,
    elements: [pokemonTypes.WATER],
  },
  {
    name: 'Jolteon',
    levelRate: [16, 100],
    pokedexId: 135,
    elements: [pokemonTypes.ELECTRIC],
  },
  {
    name: 'Flareon',
    levelRate: [16, 100],
    pokedexId: 136,
    elements: [pokemonTypes.FIRE],
  },
  {
    name: 'Porygon',
    levelRate: [1, 25],
    pokedexId: 137,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Omanyte',
    levelRate: [1, 16],
    pokedexId: 138,
    elements: [pokemonTypes.ROCK, pokemonTypes.WATER],
  },
  {
    name: 'Omastar',
    levelRate: [40, 100],
    pokedexId: 139,
    elements: [pokemonTypes.ROCK, pokemonTypes.WATER],
  },
  {
    name: 'Kabuto',
    levelRate: [1, 15],
    pokedexId: 140,
    elements: [pokemonTypes.ROCK, pokemonTypes.WATER],
  },
  {
    name: 'Kabutops',
    levelRate: [20, 100],
    pokedexId: 141,
    elements: [pokemonTypes.ROCK, pokemonTypes.WATER],
  },
  {
    name: 'Aerodactyl',
    levelRate: [20, 100],
    pokedexId: 142,
    elements: [pokemonTypes.ROCK, pokemonTypes.FLYING],
  },
  {
    name: 'Snorlax',
    levelRate: [25, 100],
    pokedexId: 143,
    elements: [pokemonTypes.NORMAL],
  },
  {
    name: 'Articuno',
    levelRate: [100, 100],
    pokedexId: 144,
    elements: [pokemonTypes.ICE, pokemonTypes.FLYING],
  },
  {
    name: 'Zapdos',
    levelRate: [100, 100],
    pokedexId: 145,
    elements: [pokemonTypes.ELECTRIC, pokemonTypes.FLYING],
  },
  {
    name: 'Moltres',
    levelRate: [100, 100],
    pokedexId: 146,
    elements: [pokemonTypes.FIRE, pokemonTypes.FLYING],
  },
  {
    name: 'Dratini',
    levelRate: [1, 15],
    pokedexId: 147,
    elements: [pokemonTypes.DRAGON],
  },
  {
    name: 'Dragonair',
    levelRate: [15, 35],
    pokedexId: 148,
    elements: [pokemonTypes.DRAGON],
  },
  {
    name: 'Dragonite',
    levelRate: [36, 100],
    pokedexId: 149,
    elements: [pokemonTypes.DRAGON, pokemonTypes.FLYING],
  },
  {
    name: 'Mewtwo',
    levelRate: [100, 100],
    pokedexId: 150,
    elements: [pokemonTypes.PSYCHIC],
  },
  {
    name: 'Mew',
    levelRate: [100, 100],
    pokedexId: 151,
    elements: [pokemonTypes.PSYCHIC],
  },
];
